services:
  # Frontend React - Vetrina Landing Page
  vetrina-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ravai_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    # Esponi temporaneamente una porta per test diretto (rimuovi dopo il test)
    ports:
      - "8099:80"
    networks:
      - web-proxy

networks:
  web-proxy:
    external: true