services:
  # Frontend React - Vetrina Landing Page
  vetrina-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ravai_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    networks:
      - web-proxy

networks:
  web-proxy:
    external: true